GET http://localhost:5000/books

###
GET http://localhost:5000/books/2

###
POST http://localhost:5000/books
Content-Type: application/json

{
    "category": "Horror",
    "title": "KKN di Desa Penari",
    "author": "Simpleman",
    "publication": "2019",
    "stock": 15
}

###
PATCH http://localhost:5000/books/3
Content-Type: application/json

{
    "category": "Fiction",
    "title": "Hilmy Milan",
    "author": "Nadia Ristivani",
    "publication": "2021",
    "stock": 15
}

###
DELETE http://localhost:5000/books/2
